services:
  app-dev:
    image: golang:1.24
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/main.go
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    environment:
      - ENV_FILE=.env.dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  db_data: