### Register
POST http://auth.local/register
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

### Login
POST http://auth.local/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

### JWT
@token = jwt here

### Protected
GET http://myapp.local/protected
Authorization: Bearer {{token}}

### Public
GET http://myapp.local/public

### Unregister
DELETE http://auth.local/unregister
Authorization: Bearer {{token}}

### Auth
POST http://auth.local/auth
Authorization: Bearer {{token}}

### Health
GET http://auth.local/health